/**
 * Reading the published forecast artifacts.
 *
 * The frontend reads JSON that the Python pipeline wrote — **it never
 * computes a probability of its own.** That separation is deliberate and
 * load-bearing: a number rendered on the page must be traceable to a
 * specific artifact, generated by a specific model version, from a specific
 * corpus. A component that quietly recomputes something is a second model
 * nobody benchmarked.
 *
 * Every accessor here returns `null` rather than a default when the artifact
 * is missing. **Absent data is rendered as absent**, never as zero — a 0%
 * championship probability and "we have not run the forecast" look identical
 * on a page and mean completely different things.
 */

import fs from 'node:fs'
import path from 'node:path'

const PREDICTIONS_DIR = path.join(process.cwd(), 'backend', 'data', 'predictions')
const DIAGNOSTICS_DIR = path.join(process.cwd(), 'backend', 'data', 'diagnostics')

export interface TeamProjection {
  team_id: number
  name: string
  abbreviation: string
  conference: string
  division: string
  wins: number
  losses: number
  ties: number
  wins_p10: number
  wins_p90: number
  p_division: number
  p_playoffs: number
  p_bye: number
  p_top_seed: number
  p_divisional_round: number
  p_conference_game: number
  p_conference_title: number
  p_championship: number
  seed_distribution: Record<string, number>
  current_wins: number
  current_losses: number
  current_ties: number
  games_left: number
  elo: number
}

export interface SeasonProjections {
  season: number
  simulations: number
  games_played: number
  games_remaining: number
  generated_at: string
  seeds_per_conference: number
  model_version: string
  teams: TeamProjection[]
}

export interface SpreadRow {
  line: number
  home_cover: number
  push: number
  away_cover: number
}

export interface MarginDistributionData {
  low: number
  high: number
  p: number[]
  outside: number
}

export interface GameForecast {
  game_id: string
  season: number
  week: number
  date_utc: string
  home_team_id: number
  away_team_id: number
  home: string
  away: string
  home_name: string
  away_name: string
  neutral_site: boolean
  venue: string | null
  p_home: number
  p_tie: number
  p_away: number
  exp_margin: number
  exp_total: number
  exp_home_score: number
  exp_away_score: number
  margin_sd: number
  total_sd: number
  margin_distribution: MarginDistributionData
  spread_surface: SpreadRow[]
  market: {
    ml_home: number | null
    ml_away: number | null
    spread_home: number | null
    total_points: number | null
    provider: string | null
  }
}

export interface GameForecasts {
  season: number
  generated_at: string
  model_version: string
  season_start: string | null
  weeks_in_season: number
  games: GameForecast[]
}

export interface PowerRating {
  team_id: number
  name: string
  abbreviation: string
  conference: string
  division: string
  elo: number
}

export interface PowerRatings {
  season: number
  generated_at: string
  carryover_applied: boolean
  teams: PowerRating[]
}

export interface ScoreCard {
  n: number
  brier: number
  log_loss: number
  accuracy: number
  ece: number
  ties_excluded: number
  brier_ties_as_half?: number
}

export interface MarketBenchmark {
  generated_at: string
  corpus_games: number
  scored_games: number
  first_scored_season: number
  warmup_seasons: number
  devig_method: string
  refit_cadence: string
  priced_games: number
  unpriced_games: number
  market_source_counts: Record<string, number>
  base_rate: number
  scorecards: Record<string, ScoreCard>
  paired_vs_market: Record<
    string,
    { mean: number; lo: number; hi: number; p_better: number }
  >
  note: string
}

function readJson<T>(dir: string, file: string): T | null {
  try {
    const raw = fs.readFileSync(path.join(dir, file), 'utf8')
    return JSON.parse(raw) as T
  } catch {
    // Missing or malformed is "we have not published this", which is a fact
    // the page renders. It is never a reason to invent a value.
    return null
  }
}

export function getSeasonProjections(): SeasonProjections | null {
  return readJson<SeasonProjections>(PREDICTIONS_DIR, 'season_projections.json')
}

export function getGameForecasts(): GameForecasts | null {
  return readJson<GameForecasts>(PREDICTIONS_DIR, 'game_forecasts.json')
}

export function getPowerRatings(): PowerRatings | null {
  return readJson<PowerRatings>(PREDICTIONS_DIR, 'power_ratings.json')
}

export function getMarketBenchmark(): MarketBenchmark | null {
  return readJson<MarketBenchmark>(DIAGNOSTICS_DIR, 'market_benchmark.json')
}

/**
 * The next slate to play, as a week number.
 *
 * **Anchored on the earliest fixture that has not kicked off**, not on
 * "today's date mapped to a week". The NFL flexes games between Sunday and
 * Monday and plays on Thursdays, so a date-to-week function is wrong for
 * part of every week; the schedule itself is the authority on which week is
 * next.
 */
export function currentWeek(forecasts: GameForecasts | null): number | null {
  if (!forecasts || forecasts.games.length === 0) return null
  const now = Date.now()
  const upcoming = forecasts.games
    .filter((g) => new Date(g.date_utc).getTime() >= now)
    .sort((a, b) => a.date_utc.localeCompare(b.date_utc))
  return (upcoming[0] ?? forecasts.games[0]).week
}

export function gamesForWeek(
  forecasts: GameForecasts | null,
  week: number,
): GameForecast[] {
  if (!forecasts) return []
  return forecasts.games
    .filter((g) => g.week === week)
    .sort((a, b) => a.date_utc.localeCompare(b.date_utc))
}

/** Group projections by division, conference first. */
export function byDivision(
  teams: TeamProjection[],
): { conference: string; division: string; teams: TeamProjection[] }[] {
  const groups = new Map<string, TeamProjection[]>()
  for (const team of teams) {
    const key = `${team.conference}||${team.division}`
    const list = groups.get(key)
    if (list) list.push(team)
    else groups.set(key, [team])
  }
  return [...groups.entries()]
    .map(([key, list]) => {
      const [conference, division] = key.split('||')
      return {
        conference,
        division,
        teams: [...list].sort((a, b) => b.wins - a.wins),
      }
    })
    .sort((a, b) =>
      a.conference === b.conference
        ? a.division.localeCompare(b.division)
        : a.conference.localeCompare(b.conference),
    )
}
