/** Real-artifact browser audit. Set BROWSER_TEST_MODULE_ROOT if using shared tooling. */
import { createRequire } from 'node:module'
import fs from 'node:fs/promises'
import path from 'node:path'
import assert from 'node:assert/strict'
const require = createRequire(path.join(process.env.BROWSER_TEST_MODULE_ROOT || process.cwd(),'package.json'))
const { chromium } = require('playwright')
const axePath = require.resolve('axe-core/axe.min.js')
const base = process.env.BASE_URL || 'http://127.0.0.1:3012'
const output = process.env.AUDIT_OUTPUT || '/tmp/nfl-forecast-lab-audit'
await fs.mkdir(output,{recursive:true})
const browser = await chromium.launch({headless:true,args:['--no-sandbox']})
const context = await browser.newContext({reducedMotion:'reduce'})
const page = await context.newPage()
page.setDefaultTimeout(60000)
page.setDefaultNavigationTimeout(120000)
const errors=[]
page.on('pageerror',e=>errors.push(e.message))
try {
  const res=await page.goto(`${base}/lab`,{waitUntil:'domcontentloaded',timeout:120000})
  assert.equal(res.status(),200)
  await page.getByRole('heading',{name:'Read the game. Play it out.'}).waitFor()
  console.log('Lab page loaded')
  const response=await page.request.get(`${base}/api/forecast-lab`)
  assert.equal(response.status(),200)
  const data=await response.json()
  const auditNow=process.env.AUDIT_USE_PUBLICATION_TIME==='1'?Date.parse(data.forecast.generated_at):Date.now()
  if(process.env.AUDIT_USE_PUBLICATION_TIME==='1') await page.clock.install({time:new Date(auditNow)})
  const game=data.forecast.games.find(g=>Date.parse(g.date_utc)>auditNow)
  assert.ok(game,'Need a real upcoming forecast to exercise the lab')
  await page.goto(`${base}/lab?game=${game.game_id}`,{waitUntil:'domcontentloaded'})
  await page.waitForFunction(()=>document.querySelector('select')?.value==='all')
  await page.getByTestId('home-probability').waitFor()
  assert.equal(await page.getByTestId('home-probability').innerText(),`${(game.p_home*100).toFixed(1)}%`)
  assert.equal(await page.getByTestId('away-probability').innerText(),`${(game.p_away*100).toFixed(1)}%`)
  await page.getByRole('button',{name:`Follow ${game.home_name}`,exact:true}).click()
  await page.reload({waitUntil:'domcontentloaded'})
  await page.getByRole('button',{name:`Unfollow ${game.home_name}`,exact:true}).waitFor()
  const scenario=data.scenarios?.games.find(s=>s.game_id===game.game_id)
  assert.ok(scenario,'Published next-week fixture must have a validated scenario')
  const stakes=page.getByRole('region',{name:'Playoff stakes',exact:true})
  const branch=scenario.branches.home
  await stakes.getByRole('button',{name:`${game.home} wins`,exact:true}).click()
  const homeScenario=branch.teams.find(t=>t.team_id===game.home_team_id)
  assert.equal(await page.getByTestId(`scenario-${game.home}`).innerText(),`${(homeScenario.p_playoffs*100).toFixed(1)}%`)
  assert.match(await page.getByTestId('scenario-basis').innerText(),new RegExp(branch.samples.toLocaleString('en-US')))
  assert.equal(await page.getByTestId('home-probability').innerText(),`${(game.p_home*100).toFixed(1)}%`)
  if(!scenario.branches.tie.available) assert.equal(await stakes.getByRole('button',{name:'Tie',exact:true}).isDisabled(),true)
  await stakes.getByRole('button',{name:'Baseline',exact:true}).click()
  await page.getByText('Try a simple record scenario',{exact:true}).click()
  const records=page.getByRole('region',{name:'Record scenario',exact:true})
  const t=data.teams.find(t=>t.abbreviation===game.home)
  if(t) {
    await records.getByRole('button',{name:`${game.home} wins`,exact:true}).click()
    assert.equal(await page.getByTestId('home-record').innerText(),`${t.current_wins+1}–${t.current_losses}–${t.current_ties}`)
    await records.getByRole('button',{name:'Tie',exact:true}).click()
    assert.equal(await page.getByTestId('home-record').innerText(),`${t.current_wins}–${t.current_losses}–${t.current_ties+1}`)
    assert.equal(await page.getByTestId('home-probability').innerText(),`${(game.p_home*100).toFixed(1)}%`)
  }
  await page.locator('.lab-fixture').nth(1).click()
  await page.getByRole('searchbox',{name:'Search teams'}).fill('filtered-away')
  await page.goBack({waitUntil:'domcontentloaded'})
  await page.waitForFunction(()=>document.querySelector('input[type=search]')?.value==='')
  assert.equal(await page.getByTestId('home-probability').innerText(),`${(game.p_home*100).toFixed(1)}%`)
  console.log('Probability parity, following, scenarios, and browser back passed')
  await page.getByRole('searchbox',{name:'Search teams'}).fill('no matching franchise')
  await page.getByText('No games match these filters.').waitFor()
  await page.getByRole('button',{name:'Reset filters'}).click()
  const slider=page.getByRole('slider').first()
  await slider.focus();await page.keyboard.press('ArrowRight')
  await page.getByRole('button',{name:'Share game',exact:true}).click()
  await page.getByText(/Game link copied\.|Share this game:/).waitFor()
  assert.match(await page.locator('p[role="status"]').innerText(),/copied|Share this game/)
  await page.getByRole('button',{name:'Refresh forecasts',exact:true}).click()
  await page.getByText('Latest published forecasts loaded.').waitFor()
  await page.route('**/api/forecast-lab',r=>r.fulfill({status:503,body:'unavailable'}))
  await page.getByRole('button',{name:'Refresh forecasts',exact:true}).click()
  await page.getByText('Refresh unavailable. Your last loaded forecasts are still here.').waitFor()
  await page.getByTestId('home-probability').waitFor()
  await page.unroute('**/api/forecast-lab')
  await page.getByRole('button',{name:'Refresh forecasts',exact:true}).click()
  await page.getByText('Latest published forecasts loaded.').waitFor()
  await page.getByRole('combobox',{name:'Week',exact:true}).selectOption('next')
  console.log('Interactions passed; checking four viewport widths')
  const checks=[]
  for (const width of [320,390,768,1440]) {
    await page.setViewportSize({width,height:1000})
    await page.addScriptTag({path:axePath})
    const evaluation=page.evaluate(async()=>({
      overflow:document.documentElement.scrollWidth>innerWidth,
      axe:(await window.axe.run('#main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),
      overlay:!!document.querySelector('[data-nextjs-dialog]'),
    }))
    let limit
    const result=await Promise.race([evaluation,new Promise((_,reject)=>{limit=setTimeout(()=>reject(new Error(`Accessibility audit timed out at ${width}px`)),60000)})]).finally(()=>clearTimeout(limit))
    await page.screenshot({path:path.join(output,`lab-${width}.png`),fullPage:true,timeout:15000})
    checks.push({width,...result})
    console.log(`Viewport ${width}: ${result.axe.length} accessibility violations, overflow=${result.overflow}`)
    assert.equal(result.overflow,false,`horizontal overflow at ${width}`)
    assert.deepEqual(result.axe,[],`accessibility failures at ${width}`)
    assert.equal(result.overlay,false)
  }
  await page.goto(`${base}/lab?game=missing`,{waitUntil:'domcontentloaded'})
  await page.getByText(/The shared game has kicked off/).waitFor()
  await page.goto(base,{waitUntil:'domcontentloaded'})
  await page.getByRole('heading',{name:'Your Sunday starts here.'}).waitFor()
  await page.getByRole('region',{name:'Week briefing',exact:true}).waitFor()
  await page.screenshot({path:path.join(output,'homepage.png'),fullPage:false,timeout:20000})
  await page.setViewportSize({width:390,height:844})
  await page.addScriptTag({path:axePath})
  const homeCheck=await page.evaluate(async()=>({overflow:document.documentElement.scrollWidth>innerWidth,axe:(await window.axe.run('#main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(v=>v.id)}))
  assert.equal(homeCheck.overflow,false,'Homepage mobile overflow')
  assert.deepEqual(homeCheck.axe,[],'Homepage accessibility')
  await page.screenshot({path:path.join(output,'homepage-mobile.png'),fullPage:false,timeout:20000})
  await page.getByRole('link',{name:'Open the lab ↗'}).click()
  await page.getByRole('heading',{name:'Read the game. Play it out.'}).waitFor()
  await page.goto(`${base}/accuracy`,{waitUntil:'domcontentloaded'})
  await page.getByRole('heading',{name:/Published forecast record/}).waitFor()
  await page.getByRole('region',{name:'Model development',exact:true}).waitFor()
  assert.deepEqual(errors,[])
  await fs.writeFile(path.join(output,'results.json'),JSON.stringify({generated_at:new Date().toISOString(),checks,home:homeCheck,errors,clock:process.env.AUDIT_USE_PUBLICATION_TIME==='1'?'publication':'current',game_id:game.game_id,passed:true},null,2))
  console.log(JSON.stringify({passed:true,viewports:checks.map(c=>c.width),game:game.game_id,output}))
} catch (error) {
  await page.screenshot({path:path.join(output,'failure.png'),fullPage:true,timeout:15000}).catch(()=>{})
  await fs.writeFile(path.join(output,'failure.txt'),String(error)+'\n'+await page.locator('body').innerText().catch(()=>''))
  throw error
} finally { await browser.close() }
